version: '3.1'

services:
  wp:
    build:
      context: .
      args:
        wp_version: ${WP_VERSION}
    image: ${IMAGE_NAME}
    volumes:
      - ./html:/var/www/html
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      MYSQL_CHARSET: ${MYSQL_CHARSET}
      WORDPRESS_TABLE_PREFIX: ${MYSQL_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_DISPLAY', false);
        define('WP_DEBUG_LOG', true);
        define('WP_POST_REVISIONS', false);
        define('WP_REDIS_HOST', 'wpredis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_TIMEOUT', 1);
        define('WP_REDIS_READ_TIMEOUT', 1);
        define('WP_REDIS_DATABASE', 0);

  # Redis
  wpredis:
    container_name: wpredis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./redis:/data

  # MySQL
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - mysql

volumes:
  html:
  mysql:
  redis:
